import type {
  Auction,
  ExportGuideSection,
  MineDashboard,
  Product,
  Shipment,
  VirtualTour,
} from './types';

const now = Date.now();
const hours = (n: number) => new Date(now + n * 3600_000).toISOString();
const daysAgo = (n: number) => new Date(now - n * 86_400_000).toISOString();

export const products: Product[] = [
  {
    id: 'p-marmarit-lashtor',
    code: 'SL-1042',
    title: 'اسلب مرمریت لاشتر',
    titleEn: 'Lashtar marble slab',
    category: 'slab',
    colorHex: '#D9CFC0',
    pricePerUnit: 1_850_000,
    unit: 'm2',
    minOrder: 40,
    stockQuantity: 620,
    mineId: 'm-lashtor',
    mineName: 'معدن لاشتر اصفهان',
    mineNameEn: 'Lashtar mine, Isfahan',
    city: 'اصفهان',
    rating: 4.6,
    specs: {
      dimensions: '۲۸۰ × ۱۶۰ سانتی‌متر',
      thicknessMm: 20,
      waterAbsorption: '۰.۳٪',
      compressiveStrength: '۸۵ MPa',
      finish: 'polished',
    },
    tags: ['نما', 'کف', 'مدرن'],
  },
  {
    id: 'p-travertine-azarshahr',
    code: 'SL-2071',
    title: 'تراورتن آذرشهر عباس‌آباد',
    titleEn: 'Azarshahr travertine',
    category: 'slab',
    colorHex: '#E8D8BE',
    pricePerUnit: 1_320_000,
    unit: 'm2',
    minOrder: 60,
    stockQuantity: 940,
    mineId: 'm-azarshahr',
    mineName: 'معدن آذرشهر',
    mineNameEn: 'Azarshahr mine',
    city: 'تبریز',
    rating: 4.8,
    specs: {
      dimensions: '۲۴۰ × ۱۲۰ سانتی‌متر',
      thicknessMm: 18,
      waterAbsorption: '۱.۲٪',
      compressiveStrength: '۶۸ MPa',
      finish: 'honed',
    },
    tags: ['نما', 'کلاسیک', 'صادراتی'],
  },
  {
    id: 'p-granite-natanz',
    code: 'BL-3310',
    title: 'کوپ گرانیت نطنز',
    titleEn: 'Natanz granite block',
    category: 'block',
    colorHex: '#5B5F66',
    pricePerUnit: 42_000_000,
    unit: 'ton',
    minOrder: 5,
    stockQuantity: 86,
    mineId: 'm-natanz',
    mineName: 'معدن گرانیت نطنز',
    mineNameEn: 'Natanz granite mine',
    city: 'نطنز',
    rating: 4.4,
    specs: {
      dimensions: '۲۸۰ × ۱۵۰ × ۱۲۰ سانتی‌متر',
      thicknessMm: 0,
      waterAbsorption: '۰.۲٪',
      compressiveStrength: '۱۵۰ MPa',
      finish: 'flamed',
    },
    tags: ['کوپ', 'ترافیک سنگین', 'دوام بالا'],
  },
  {
    id: 'p-onyx-mahallat',
    code: 'SL-5501',
    title: 'اسلب چینی محلات',
    titleEn: 'Mahallat onyx slab',
    category: 'slab',
    colorHex: '#F0E6D2',
    pricePerUnit: 3_400_000,
    unit: 'm2',
    minOrder: 20,
    stockQuantity: 180,
    mineId: 'm-mahallat',
    mineName: 'معدن محلات',
    mineNameEn: 'Mahallat mine',
    city: 'محلات',
    rating: 4.9,
    specs: {
      dimensions: '۳۰۰ × ۱۸۰ سانتی‌متر',
      thicknessMm: 20,
      waterAbsorption: '۰.۲٪',
      compressiveStrength: '۹۲ MPa',
      finish: 'polished',
    },
    tags: ['لاکچری', 'دیوار داخلی', 'نورپذیر'],
  },
  {
    id: 'p-tile-dehbid',
    code: 'TL-7712',
    title: 'تایل مرمریت دهبید',
    titleEn: 'Dehbid marble tile',
    category: 'tile',
    colorHex: '#CFC6B4',
    pricePerUnit: 980_000,
    unit: 'm2',
    minOrder: 100,
    stockQuantity: 2_400,
    mineId: 'm-dehbid',
    mineName: 'معدن دهبید فارس',
    mineNameEn: 'Dehbid mine, Fars',
    city: 'شیراز',
    rating: 4.5,
    specs: {
      dimensions: '۶۰ × ۶۰ سانتی‌متر',
      thicknessMm: 15,
      waterAbsorption: '۰.۴٪',
      compressiveStrength: '۸۰ MPa',
      finish: 'honed',
    },
    tags: ['کف', 'مینیمال', 'پله'],
  },
  {
    id: 'p-black-najafabad',
    code: 'SL-6180',
    title: 'اسلب مشکی نجف‌آباد',
    titleEn: 'Najafabad black slab',
    category: 'slab',
    colorHex: '#2B2B2F',
    pricePerUnit: 2_150_000,
    unit: 'm2',
    minOrder: 30,
    stockQuantity: 310,
    mineId: 'm-najafabad',
    mineName: 'معدن نجف‌آباد',
    mineNameEn: 'Najafabad mine',
    city: 'نجف‌آباد',
    rating: 4.3,
    specs: {
      dimensions: '۲۶۰ × ۱۴۰ سانتی‌متر',
      thicknessMm: 20,
      waterAbsorption: '۰.۳٪',
      compressiveStrength: '۱۰۵ MPa',
      finish: 'leather',
    },
    tags: ['مدرن', 'آشپزخانه', 'لاکچری'],
  },
  {
    id: 'p-crushed-basalt',
    code: 'CR-9004',
    title: 'سنگ‌دانه بازالت',
    titleEn: 'Crushed basalt aggregate',
    category: 'crushed',
    colorHex: '#3F454C',
    pricePerUnit: 860_000,
    unit: 'ton',
    minOrder: 25,
    stockQuantity: 5_600,
    mineId: 'm-basalt',
    mineName: 'معدن بازالت قروه',
    mineNameEn: 'Qorveh basalt mine',
    city: 'قروه',
    rating: 4.1,
    specs: {
      dimensions: '۰ تا ۲۵ میلی‌متر',
      thicknessMm: 0,
      waterAbsorption: '۰.۸٪',
      compressiveStrength: '۱۴۰ MPa',
      finish: 'bushhammered',
    },
    tags: ['راه‌سازی', 'ترافیک سنگین'],
  },
  {
    id: 'p-travertine-silver',
    code: 'SL-2288',
    title: 'تراورتن سیلور موج‌دار',
    titleEn: 'Silver wave travertine',
    category: 'slab',
    colorHex: '#B9BCC2',
    pricePerUnit: 1_640_000,
    unit: 'm2',
    minOrder: 45,
    stockQuantity: 470,
    mineId: 'm-azarshahr',
    mineName: 'معدن آذرشهر',
    mineNameEn: 'Azarshahr mine',
    city: 'تبریز',
    rating: 4.7,
    specs: {
      dimensions: '۲۴۰ × ۱۲۰ سانتی‌متر',
      thicknessMm: 20,
      waterAbsorption: '۱.۰٪',
      compressiveStrength: '۷۴ MPa',
      finish: 'honed',
    },
    tags: ['نما', 'روستیک', 'صادراتی'],
  },
];

export const auctions: Auction[] = [
  {
    id: 'a-1001',
    lotCode: 'LOT-1001',
    title: 'کوپ مرمریت لاشتر درجه A',
    titleEn: 'Grade A Lashtar marble block',
    colorHex: '#D9CFC0',
    status: 'live',
    startingPrice: 780_000_000,
    currentBid: 1_190_000_000,
    bidStep: 20_000_000,
    volumeM3: 12.4,
    mineName: 'معدن لاشتر اصفهان',
    mineNameEn: 'Lashtar mine, Isfahan',
    startsAt: hours(-3),
    endsAt: hours(2),
    bids: [
      { id: 'b1', bidderLabel: 'خریدار ۴۲', amount: 1_190_000_000, placedAt: hours(-0.1), isMine: false },
      { id: 'b2', bidderLabel: 'خریدار ۱۷', amount: 1_170_000_000, placedAt: hours(-0.4), isMine: false },
      { id: 'b3', bidderLabel: 'خریدار ۸', amount: 1_120_000_000, placedAt: hours(-1.2), isMine: false },
    ],
  },
  {
    id: 'a-1002',
    lotCode: 'LOT-1002',
    title: 'کوپ گرانیت نطنز',
    titleEn: 'Natanz granite block',
    colorHex: '#5B5F66',
    status: 'live',
    startingPrice: 410_000_000,
    currentBid: 505_000_000,
    bidStep: 10_000_000,
    volumeM3: 8.1,
    mineName: 'معدن گرانیت نطنز',
    mineNameEn: 'Natanz granite mine',
    startsAt: hours(-1),
    endsAt: hours(0.6),
    bids: [
      { id: 'b4', bidderLabel: 'خریدار ۵', amount: 505_000_000, placedAt: hours(-0.2), isMine: false },
      { id: 'b5', bidderLabel: 'خریدار ۳۱', amount: 490_000_000, placedAt: hours(-0.5), isMine: false },
    ],
  },
  {
    id: 'a-1003',
    lotCode: 'LOT-1003',
    title: 'بلوک چینی محلات نورپذیر',
    titleEn: 'Translucent Mahallat onyx block',
    colorHex: '#F0E6D2',
    status: 'upcoming',
    startingPrice: 1_250_000_000,
    currentBid: 1_250_000_000,
    bidStep: 50_000_000,
    volumeM3: 6.2,
    mineName: 'معدن محلات',
    mineNameEn: 'Mahallat mine',
    startsAt: hours(19),
    endsAt: hours(27),
    bids: [],
  },
  {
    id: 'a-1004',
    lotCode: 'LOT-0994',
    title: 'کوپ تراورتن عباس‌آباد',
    titleEn: 'Abbasabad travertine block',
    colorHex: '#E8D8BE',
    status: 'ended',
    startingPrice: 320_000_000,
    currentBid: 468_000_000,
    bidStep: 10_000_000,
    volumeM3: 9.7,
    mineName: 'معدن آذرشهر',
    mineNameEn: 'Azarshahr mine',
    startsAt: hours(-30),
    endsAt: hours(-6),
    bids: [
      { id: 'b6', bidderLabel: 'شما', amount: 468_000_000, placedAt: hours(-6.2), isMine: true },
      { id: 'b7', bidderLabel: 'خریدار ۲۲', amount: 455_000_000, placedAt: hours(-6.6), isMine: false },
    ],
  },
];

export const mineDashboard: MineDashboard = {
  efficiency: 0.87,
  monthlyOutputTons: 1_840,
  inventory: [
    { id: 'i1', batchCode: 'BC-2401', category: 'block', quantity: 34, unit: 'ton', grade: 'A', extractedAt: daysAgo(4), status: 'ready' },
    { id: 'i2', batchCode: 'BC-2402', category: 'slab', quantity: 620, unit: 'm2', grade: 'A', extractedAt: daysAgo(9), status: 'ready' },
    { id: 'i3', batchCode: 'BC-2403', category: 'slab', quantity: 210, unit: 'm2', grade: 'B', extractedAt: daysAgo(2), status: 'processing' },
    { id: 'i4', batchCode: 'BC-2404', category: 'tile', quantity: 2_400, unit: 'm2', grade: 'A', extractedAt: daysAgo(14), status: 'reserved' },
    { id: 'i5', batchCode: 'BC-2405', category: 'block', quantity: 52, unit: 'ton', grade: 'C', extractedAt: daysAgo(1), status: 'raw' },
  ],
  production: [
    { label: 'شنبه', labelEn: 'Sat', output: 210, capacity: 260 },
    { label: 'یک‌شنبه', labelEn: 'Sun', output: 245, capacity: 260 },
    { label: 'دوشنبه', labelEn: 'Mon', output: 190, capacity: 260 },
    { label: 'سه‌شنبه', labelEn: 'Tue', output: 255, capacity: 260 },
    { label: 'چهارشنبه', labelEn: 'Wed', output: 232, capacity: 260 },
    { label: 'پنج‌شنبه', labelEn: 'Thu', output: 178, capacity: 260 },
  ],
  workOrders: [
    { id: 'w1', code: 'WO-118', title: 'برش کوپ BC-2401 به اسلب', titleEn: 'Cut block BC-2401 into slabs', assignee: 'خط برش ۲', due: hours(30), progress: 0.65, priority: 'high' },
    { id: 'w2', code: 'WO-119', title: 'ساب و پولیش بچ BC-2403', titleEn: 'Polish batch BC-2403', assignee: 'خط پولیش ۱', due: hours(54), progress: 0.3, priority: 'normal' },
    { id: 'w3', code: 'WO-120', title: 'بسته‌بندی سفارش صادراتی چین', titleEn: 'Package the China export order', assignee: 'انبار مرکزی', due: hours(96), progress: 0.1, priority: 'high' },
    { id: 'w4', code: 'WO-121', title: 'سرویس دوره‌ای دستگاه سیم‌برش', titleEn: 'Wire-saw maintenance', assignee: 'تعمیرات', due: hours(150), progress: 0, priority: 'low' },
  ],
};

export const shipments: Shipment[] = [
  {
    id: 's-8801',
    trackingCode: 'SB-8801-IR',
    productTitle: 'اسلب مرمریت لاشتر — ۳۲۰ متر مربع',
    productTitleEn: 'Lashtar marble slab — 320 m²',
    origin: 'اصفهان، معدن لاشتر',
    originEn: 'Isfahan, Lashtar mine',
    destination: 'تهران، انبار کارفرما',
    destinationEn: 'Tehran, client warehouse',
    carrier: 'باربری سنگ‌رو',
    carrierEn: 'SangRo Freight',
    weightTons: 21.4,
    eta: hours(26),
    international: false,
    stages: [
      { key: 'order', status: 'done', at: daysAgo(6) },
      { key: 'extraction', status: 'done', at: daysAgo(5) },
      { key: 'processing', status: 'done', at: daysAgo(2) },
      { key: 'transport', status: 'active', at: hours(-8), note: 'در مسیر اصفهان به تهران', noteEn: 'On the road from Isfahan to Tehran' },
      { key: 'delivery', status: 'pending' },
    ],
  },
  {
    id: 's-8802',
    trackingCode: 'SB-8802-CN',
    productTitle: 'کوپ گرانیت نطنز — ۲ کانتینر',
    productTitleEn: 'Natanz granite block — 2 containers',
    origin: 'بندر عباس',
    originEn: 'Bandar Abbas',
    destination: 'شیامن، چین',
    destinationEn: 'Xiamen, China',
    carrier: 'خط کشتیرانی خلیج',
    carrierEn: 'Gulf Shipping Line',
    weightTons: 48,
    eta: hours(430),
    international: true,
    stages: [
      { key: 'order', status: 'done', at: daysAgo(21) },
      { key: 'extraction', status: 'done', at: daysAgo(17) },
      { key: 'processing', status: 'done', at: daysAgo(11) },
      { key: 'customs', status: 'active', at: hours(-20), note: 'در حال ترخیص در بندر عباس', noteEn: 'Clearing customs at Bandar Abbas' },
      { key: 'transport', status: 'pending' },
      { key: 'delivery', status: 'pending' },
    ],
  },
  {
    id: 's-8803',
    trackingCode: 'SB-8803-IR',
    productTitle: 'تایل دهبید — ۱٬۲۰۰ متر مربع',
    productTitleEn: 'Dehbid tile — 1,200 m²',
    origin: 'شیراز',
    originEn: 'Shiraz',
    destination: 'مشهد',
    destinationEn: 'Mashhad',
    carrier: 'حمل‌ونقل پارس',
    carrierEn: 'Pars Transport',
    weightTons: 33.6,
    eta: hours(-4),
    international: false,
    stages: [
      { key: 'order', status: 'done', at: daysAgo(12) },
      { key: 'extraction', status: 'done', at: daysAgo(10) },
      { key: 'processing', status: 'done', at: daysAgo(6) },
      { key: 'transport', status: 'done', at: daysAgo(2) },
      { key: 'delivery', status: 'done', at: hours(-4) },
    ],
  },
];

export const virtualTours: VirtualTour[] = [
  { id: 't-lashtor', mineName: 'معدن لاشتر', mineNameEn: 'Lashtar mine', city: 'اصفهان', cityEn: 'Isfahan', scenes: 12, coverColor: '#D9CFC0' },
  { id: 't-natanz', mineName: 'معدن گرانیت نطنز', mineNameEn: 'Natanz granite mine', city: 'نطنز', cityEn: 'Natanz', scenes: 9, coverColor: '#5B5F66' },
  { id: 't-mahallat', mineName: 'معدن محلات', mineNameEn: 'Mahallat mine', city: 'محلات', cityEn: 'Mahallat', scenes: 15, coverColor: '#F0E6D2' },
];

export const exportGuide: ExportGuideSection[] = [
  {
    id: 'g-docs',
    title: 'مدارک لازم برای صادرات سنگ',
    titleEn: 'Documents required to export stone',
    body: 'پروفرما، فاکتور تجاری، بارنامه، گواهی مبدأ اتاق بازرگانی، لیست بسته‌بندی و کد اقتصادی صادرکننده. برای سنگ فرآوری‌شده، گواهی آزمون فنی نیز درخواست می‌شود.',
    bodyEn: 'Proforma, commercial invoice, bill of lading, chamber-of-commerce certificate of origin, packing list and the exporter tax code. Processed stone also needs a technical test certificate.',
  },
  {
    id: 'g-incoterms',
    title: 'انتخاب شرایط تحویل (اینکوترمز)',
    titleEn: 'Choosing the incoterm',
    body: 'برای خریدار تازه، FOB بندرعباس رایج‌ترین انتخاب است. CIF ریسک حمل را به عهده فروشنده می‌گذارد و معمولاً ۸ تا ۱۲ درصد به قیمت اضافه می‌کند.',
    bodyEn: 'FOB Bandar Abbas is the most common choice for a new buyer. CIF puts the freight risk on the seller and usually adds 8–12% to the price.',
  },
  {
    id: 'g-packing',
    title: 'استاندارد بسته‌بندی دریایی',
    titleEn: 'Sea-freight packing standard',
    body: 'اسلب‌ها در باندل چوبی با فوم بین لایه‌ها و تسمه فلزی بسته می‌شوند. هر کانتینر ۲۰ فوت حداکثر ۲۴ تن بار مجاز دارد.',
    bodyEn: 'Slabs travel in wooden bundles with foam between layers and steel strapping. A 20-foot container carries at most 24 tonnes.',
  },
  {
    id: 'g-payment',
    title: 'روش‌های پرداخت بین‌المللی',
    titleEn: 'International payment methods',
    body: 'اعتبار اسنادی (LC)، حواله ارزی و پرداخت از طریق صرافی‌های مجاز. برای سفارش اول، پیش‌پرداخت ۳۰ درصد و تسویه پیش از بارگیری متداول است.',
    bodyEn: 'Letter of credit, wire transfer, or licensed exchange houses. A 30% deposit with the balance before loading is standard for a first order.',
  },
];

export const countries = [
  { code: 'CN', fa: 'چین', en: 'China', flag: '🇨🇳' },
  { code: 'SA', fa: 'عربستان', en: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'AE', fa: 'امارات', en: 'UAE', flag: '🇦🇪' },
  { code: 'IQ', fa: 'عراق', en: 'Iraq', flag: '🇮🇶' },
  { code: 'TR', fa: 'ترکیه', en: 'Türkiye', flag: '🇹🇷' },
  { code: 'IN', fa: 'هند', en: 'India', flag: '🇮🇳' },
  { code: 'US', fa: 'آمریکا', en: 'United States', flag: '🇺🇸' },
  { code: 'GB', fa: 'انگلستان', en: 'United Kingdom', flag: '🇬🇧' },
] as const;

/** Indicative rates against 1 toman, used by the trade module's converter. */
export const currencyRates = {
  IRT: 1,
  USD: 1 / 92_000,
  EUR: 1 / 99_500,
  AED: 1 / 25_000,
  CNY: 1 / 12_800,
} as const;

export type CurrencyCode = keyof typeof currencyRates;

/** Pre-modelled scenes Renderan applies a texture to. */
export const renderProjects: import('./types').RenderProject[] = [
  {
    id: 'rp-lobby',
    title: 'لابی ساختمان مسکونی',
    titleEn: 'Residential lobby',
    space: 'floor',
    surface: 'floor',
    sceneColor: '#1E2A38',
    accentColor: '#C9A227',
    coverage: 0.52,
  },
  {
    id: 'rp-facade',
    title: 'نمای ساختمان اداری',
    titleEn: 'Office building facade',
    space: 'facade',
    surface: 'facade',
    sceneColor: '#25313F',
    accentColor: '#5B8CC4',
    coverage: 0.68,
  },
  {
    id: 'rp-kitchen',
    title: 'اپن و کانتر آشپزخانه',
    titleEn: 'Kitchen island and counter',
    space: 'kitchen',
    surface: 'counter',
    sceneColor: '#2B2F36',
    accentColor: '#E5E0D6',
    coverage: 0.44,
  },
  {
    id: 'rp-bath',
    title: 'دیوار سرویس بهداشتی',
    titleEn: 'Bathroom wall',
    space: 'bathroom',
    surface: 'wall',
    sceneColor: '#232B33',
    accentColor: '#9FB8C8',
    coverage: 0.6,
  },
  {
    id: 'rp-stairs',
    title: 'راه‌پله و پاگرد',
    titleEn: 'Staircase and landing',
    space: 'stairs',
    surface: 'stairs',
    sceneColor: '#1F262E',
    accentColor: '#B8A88A',
    coverage: 0.48,
  },
  {
    id: 'rp-living',
    title: 'دیوار نشیمن',
    titleEn: 'Living-room feature wall',
    space: 'wall',
    surface: 'wall',
    sceneColor: '#262B33',
    accentColor: '#D6C7AE',
    coverage: 0.56,
  },
];
